version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_APP_BASE_URL=https://graphql.anilist.co
      - NODE_ENV=development
